apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.service.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    tier: backend
    app: {{ .Values.nginx.service.name }}
spec:
  selector:
    app: {{ .Values.nginx.name }}
    tier: backend
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.port }}
  type: LoadBalancer
