apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.config.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    tier: backend
data:
  config : |
    map $sent_http_content_type $expires {
      "text/html"                 epoch;
      "text/html; charset=utf-8"  epoch;
      default                     off;
    }
    server {
      index index.php index.html;
      server_name localhost;
      error_log       /var/log/nginx/error.log;
      access_log      /var/log/nginx/access.log;
      root            /var/www/public;
      gzip            on;
      gzip_types      text/plain application/xml text/css application/javascript;
      gzip_min_length 1000;
      charset         utf-8;


      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }

      location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass {{ .Values.php.service.name }}:{{ .Values.php.service.port }};
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
      }


      location ~ /\.(?!well-known).* {
        deny all;
      }

    }

    client_max_body_size 10G;
