apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.php.config.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    tier: backend
data:
  config : |
    file_uploads = On
    memory_limit = -1
    upload_max_filesize = 64M
    post_max_size = 64M
    max_execution_time = 600
